# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kicad-templates
version    : 10.0.6
release    : 24
source     :
    - https://gitlab.com/kicad/libraries/kicad-templates/-/archive/10.0.6/kicad-templates-10.0.6.tar.gz : 18b4e3f2ed781383179c1b15a82c94e5176dc825e1c646f84e89ed50e835063b
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : KiCad project templates
description: |
    KiCad project templates
setup      : |
    %cmake
install    : |
    %cmake_install
    %install_license LICENSE.md
