name       : plutosvg
version    : 0.0.7
release    : 1
source     :
    - https://github.com/sammycage/plutosvg/archive/refs/tags/v0.0.7.tar.gz : 78561b571ac224030cdc450ca2986b4de915c2ba7616004a6d71a379bffd15f3
homepage   : https://github.com/sammycage/plutosvg/
license    : MIT
component  : programming.library
summary    : Tiny SVG rendering library in C
description: |
    PlutoSVG is a compact and efficient SVG rendering library written in C. It is specifically designed for parsing and rendering SVG documents embedded in OpenType fonts, providing an optimal balance between speed and minimal memory usage. It is also suitable for rendering scalable icons.
builddeps   :
    - pkgconfig(freetype2)
    - pkgconfig(plutovg)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   : /*
