name       : plutovg
version    : 1.1.0
release    : 1
source     :
    - https://github.com/sammycage/plutovg/archive/refs/tags/v1.1.0.tar.gz : 8aa9860519c407890668c29998e8bb88896ef6a2e6d7ce5ac1e57f18d79e1525
homepage   : https://github.com/sammycage/plutovg
license    : MIT
component  : programming.library
summary    : Tiny 2D vector graphics library in C
description: |
    PlutoVG is a standalone 2D vector graphics library in C.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   : /*
