# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kicad-footprints
version    : 10.0.6
release    : 25
source     :
    - https://gitlab.com/kicad/libraries/kicad-footprints/-/archive/10.0.6/kicad-footprints-10.0.6.tar.gz : 17827af73192ae17b479d4c502b6f569d03ed855b9d3c0b9b133b8cf1b8d3e22
homepage   : https://www.kicad.org/
license    : CC-BY-SA-4.0
component  : office.scientific
summary    : Official KiCad Footprint Libraries
description: |
    The libraries are intended to be used with KiCad.
setup      : |
    %cmake
install    : |
    %cmake_install
    %install_license LICENSE.md
