name       : usysconf-epoch
version    : 1.0.0
release    : 18
source     :
    # We need something for a source
    - https://getsol.us/sources/hotspot.txt : a12b7cb43c9d9134b5bb1b35e9096b66775d9e92e7611d1cc92b02edd6782a87
extract    : no
homepage   : https://github.com/getsolus/usysconf/
license    : GPL-2.0-only
component  : system.base
summary    : Temporary package for hosting epoch and usr-merge scripts
description: |
    Temporary package for hosting the epoch script
install    : |
    install -Dm00755 -t $installdir/usr/lib64/usysconf/      $pkgfiles/*.sh
    install -Dm00644 -t $installdir/%libdir%/systemd/system/ $pkgfiles/*.service

    install -Ddm00755 $installdir/%libdir%/systemd/system/{sysinit,multi-user}.target.wants
    ln -srv $installdir/%libdir%/systemd/system/usr-merge.service $installdir/%libdir%/systemd/system/sysinit.target.wants/usr-merge.service
    ln -srv $installdir/%libdir%/systemd/system/epoch.service     $installdir/%libdir%/systemd/system/multi-user.target.wants/epoch.service
