name       : pcsx2
version    : 2.4.0
release    : 30
source     :
    - git|https://github.com/PCSX2/pcsx2.git : v2.4.0
    - git|https://github.com/ianlancetaylor/libbacktrace.git : 793921876c981ce49759114d7bb89bb89b2d3a2d
homepage   : https://pcsx2.net
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : games.emulator
summary    : PCSX2 - The Playstation 2 Emulator
description: |
    PCSX2 is an open-source PlayStation 2 (AKA PS2) emulator. Its purpose is to emulate the PS2 hardware, using a combination of MIPS CPU Interpreters, Recompilers and a Virtual Machine which manages hardware states and PS2 system memory. This allows you to play PS2 games on your PC, with many additional features and benefits.
clang      : yes
builddeps  :
    - pkgconfig(Qt6Gui)
    - pkgconfig(Qt6Linguist)
    # pkgconfig(alsa)
    # pkgconfig(bzip2)
    # pkgconfig(fmt)
    - pkgconfig(freetype2)
    # pkgconfig(gl)
    # pkgconfig(glew)
    # pkgconfig(glib-2.0)
    # pkgconfig(harfbuzz)
    # pkgconfig(libavformat)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    # pkgconfig(liblzma)
    - pkgconfig(libpcap)
    - pkgconfig(libpng)
    # pkgconfig(libpulse)
    # pkgconfig(libudev)
    - pkgconfig(libwebp)
    # pkgconfig(libxml-2.0)
    # pkgconfig(libzip)
    # pkgconfig(libzstd)
    # pkgconfig(openssl)
    # pkgconfig(portaudio-2.0)
    - pkgconfig(plutosvg)
    - pkgconfig(plutovg)
    - pkgconfig(sdl3)
    - pkgconfig(shaderc)
    # pkgconfig(sndio)
    # pkgconfig(soundtouch)
    # pkgconfig(wayland-client)
    # pkgconfig(x11)
    # pkgconfig(xext)
    # pkgconfig(xrandr)
    - extra-cmake-modules
    # glibc-devel
    - kddockwidgets-devel
    # libaio-devel
    # p7zip
    - qt6-base-private-devel
    # zstd
setup      : |
    # Build libbacktrace
    mkdir $workdir/static-deps
    cp -R $sources/libbacktrace.git $workdir
    pushd $workdir/libbacktrace.git
        ./configure --prefix="$workdir/static-deps"
        make
        make install
    popd
    # Apply patches
    #%patch -p1 -i $pkgfiles/desktop-launcher.patch
    #patch -p1 -i $pkgfiles/fix-shaderc.patch
    # Genereate release number for appstream metainfo
    #.github/workflows/scripts/linux/generate-metainfo.sh net.pcsx2.PCSX2.metainfo.xml
    # Temporary hack to make the latest daily buildable until we update our Qt6 stack
    #sed -e 's|Qt6 6.5.3 COMPONENTS|Qt6 COMPONENTS|g' -i cmake/SearchForStuff.cmake
    # TODO: Sort out the nvidia-cg-toolkit fiasco
    %cmake_ninja -L -DCMAKE_BUILD_TYPE="Release" \
        -DCMAKE_AR="/usr/bin/gcc-ar" \
        -DCMAKE_NM="/usr/bin/gcc-nm" \
        -DCMAKE_RANLIB="/usr/bin/gcc-ranlib" \
        -DCMAKE_PREFIX_PATH="$workdir/static-deps" \
        -DGAMEINDEX_DIR="/usr/share/%package%" \
        -DUSER_CMAKE_C_FLAGS="-Wno-narrowing" \
        -DUSER_CMAKE_CXX_FLAGS="-Wno-narrowing" \
        -DDISABLE_ADVANCE_SIMD=TRUE \
        -DENABLE_VULKAN=TRUE \
        -DWAYLAND_API=ON \
        -DX11_API=ON \
        -DEXTRA_PLUGINS=FALSE \
        -DPACKAGE_MODE=TRUE \
        -DUSE_SYSTEM_SDL3=ON \
        -DXDG_STD=TRUE \
        -Dzst_DIR=/usr
build      : |
    %ninja_build
install    : |
    # Upstream does not support the traditional GNU build tooling install paths
    #install -Dm00755 $workdir/solusBuildDir/bin/pcsx2-qt $installdir/usr/share/pcsx2/bin/pcsx2-qt
    #install -Dm00755 $pkgfiles/pcsx2-qt.sh $installdir/usr/bin/pcsx2-qt.sh
    # compatibility symlinks
    #ln -srv $installdir/usr/bin/pcsx2-qt.sh $installdir/usr/bin/pcsx2-qt
    #ln -srv $installdir/usr/bin/pcsx2-qt.sh $installdir/usr/bin/pcsx2
    # patched .desktop launcher
    #install -Dm00644 $workdir/.github/workflows/scripts/linux/pcsx2-qt.desktop $installdir/usr/share/applications/net.pcsx2.PCSX2.desktop
    # need an app icon as well
    #install -Dm00644 $workdir/solusBuildDir/bin/resources/icons/AppIconLarge.png $installdir/usr/share/icons/hicolor/64x64/apps/PCSX2.png
    # pcsx2 currently initialises app vars based on the location of the bin/ dir, so run with that
    #cp -rv $workdir/solusBuildDir/bin/resources $installdir/usr/share/pcsx2/bin/
    # Install appstream metainfo
    #install -Dm00644 $workdir/net.pcsx2.PCSX2.metainfo.xml -t $installdir/usr/share/metainfo/
    %ninja_install
