name       : kddockwidgets
version    : 2.2.5
release    : 1
source     :
    - https://github.com/KDAB/KDDockWidgets/releases/download/v2.2.5/kddockwidgets-2.2.5.tar.gz : 1c202d03a0c7018aebcb249b09122d846b34298d88d0bc247a601f48c7513c89
homepage   : https://www.kdab.com/software-technologies/developer-tools/kddockwidgets/
license    : GPL-3.0-or-later
component  : programming.library
summary    : KDAB's Dock Widget Framework for Qt
description: |
    KDDockWidgets is a Qt dock widget library written by KDAB, suitable for replacing QDockWidget and implementing advanced functionalities missing in Qt.
builddeps  :
    - pkgconfig(Qt6QuickWidgets)
    - qt6-base-private-devel
setup      : |
    %cmake_ninja \
        -DKDDockWidgets_FRONTENDS='qtwidgets;qtquick' \
        -DKDDockWidgets_QT6=true
build      : |
    %ninja_build
install    : |
    %ninja_install
