name       : museeks
version    : 0.20.9
release    : 5
source     :
    - https://github.com/martpie/museeks/archive/refs/tags/0.20.9.tar.gz : 2d957cb0a7f52fdbc48a88427daa4abbdcf77b8700ab7fdd9d27624ae5f4c52f
    # Use prebuilt binary untill we package it ourselves
    - https://github.com/oven-sh/bun/releases/download/bun-v1.2.9/bun-linux-x64-baseline.zip#bun.zip : f8f969281625dcde1abed7b405f0525909641674dcd0ea4060421747de30f6db
homepage   : https://museeks.io/
license    : MIT
component  : multimedia.audio
networking : yes
summary    : A simple and clean music player.
description: |
    Museeks aims to be a simple and easy to use music player with a clean UI.
builddeps  :
    - pkgconfig(ayatana-appindicator-0.1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(openssl)
    - pkgconfig(webkit2gtk-4.1)
    - rust
environment: |
    export PATH="$PATH:$sources/bun-linux-x64-baseline"
setup      : |
    unzip $sources/bun.zip -d $sources
    bun install --frozen-lockfile
build      : |
    bun tauri build --bundles deb
install    : |
    export museeksreleasedir=$workdir/src-tauri/target/release/bundle/deb/Museeks_0.20.9_amd64/data
    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib64
    install -dm00644 $installdir/usr/share
    mv $museeksreleasedir/usr/bin/* $installdir/usr/bin
    mv $museeksreleasedir/usr/share/* $installdir/usr/share
    mv $museeksreleasedir/usr/lib/* $installdir/usr/lib64
